pages:
  image: python:3.10
  stage: build
  tags:
    - docker
  before_script:
    - python -m pip install -r requirements.txt
  script:
    - jupyter lite build --contents content --output-dir public
  artifacts:
    paths:
      - public
  only:
    refs: 
      - main
