pages:
  image: python:3.10
  stage: build
  tags:
    - docker
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade pipenv
    - pipenv install --deploy
  script:
    - pipenv run jupyter lite build --contents content --output-dir public
  artifacts:
    paths:
      - public
  only:
    refs: 
      - main
